import { storage } from "./storage";
import { db } from "./db";
import { users } from "@shared/schema";
import { eq } from "drizzle-orm";

async function seedAssignments(userId: string) {
  const assignmentData = [
    {
      userId,
      courseName: "2 Octave D Scale Proficiency",
      subject: "Orchestra",
      status: "missing",
      dueDate: "Aug 26",
      weight: 15,
      notes: "Submit before midnight to recover partial credit.",
      completed: false,
      grade: null,
      pointsPossible: 100,
      score: null,
      submittedAt: null,
      gradedAt: null,
      courseId: null,
      canvasAssignmentId: null,
      assignmentType: "assignment",
      hasSubmission: false,
      isGraded: false,
      isMissing: true,
      isLate: false,
      hasReplies: false,
    },
    {
      userId,
      courseName: "Neuroscience of Music Theory",
      subject: "Orchestra",
      status: "upcoming",
      dueDate: "Sep 28",
      weight: 10,
      notes: "Review Chapter 3 notes before starting.",
      completed: false,
      grade: null,
      pointsPossible: 100,
      score: null,
      submittedAt: null,
      gradedAt: null,
      courseId: null,
      canvasAssignmentId: null,
      assignmentType: "assignment",
      hasSubmission: false,
      isGraded: false,
      isMissing: false,
      isLate: false,
      hasReplies: false,
    },
    {
      userId,
      courseName: "Composition Analysis Exercise",
      subject: "Orchestra",
      status: "submitted_pending_grade",
      dueDate: "Today",
      weight: 20,
      notes: "Analyze the harmonic structure of Beethoven's 5th.",
      completed: false,
      grade: null,
      pointsPossible: 100,
      score: null,
      submittedAt: null,
      gradedAt: null,
      courseId: null,
      canvasAssignmentId: null,
      assignmentType: "assignment",
      hasSubmission: true,
      isGraded: false,
      isMissing: false,
      isLate: false,
      hasReplies: false,
    },
    {
      userId,
      courseName: "Theory Workbook Chapter 4",
      subject: "Orchestra",
      status: "upcoming",
      dueDate: "Tomorrow",
      weight: 5,
      notes: "Theory Workbook Ex. 4",
      completed: false,
      grade: null,
      pointsPossible: 100,
      score: null,
      submittedAt: null,
      gradedAt: null,
      courseId: null,
      canvasAssignmentId: null,
      assignmentType: "assignment",
      hasSubmission: false,
      isGraded: false,
      isMissing: false,
      isLate: false,
      hasReplies: false,
    },
    {
      userId,
      courseName: "AP Bio Research Phase",
      subject: "Biology",
      status: "no_status",
      dueDate: "Mar 9",
      weight: 25,
      notes: "Due in 4 days.",
      completed: false,
      grade: null,
      pointsPossible: 100,
      score: null,
      submittedAt: null,
      gradedAt: null,
      courseId: null,
      canvasAssignmentId: null,
      assignmentType: "assignment",
      hasSubmission: false,
      isGraded: false,
      isMissing: false,
      isLate: false,
      hasReplies: false,
    },
    {
      userId,
      courseName: "Calculus Problem Set 7",
      subject: "Mathematics",
      status: "graded_on_time",
      dueDate: "Feb 20",
      weight: 10,
      completed: true,
      grade: 95,
      notes: null,
      pointsPossible: 100,
      score: 95,
      submittedAt: null,
      gradedAt: null,
      courseId: null,
      canvasAssignmentId: null,
      assignmentType: "assignment",
      hasSubmission: true,
      isGraded: true,
      isMissing: false,
      isLate: false,
      hasReplies: false,
    },
    {
      userId,
      courseName: "English Literature Essay",
      subject: "English",
      status: "graded_on_time",
      dueDate: "Feb 15",
      weight: 15,
      completed: true,
      grade: 92,
      notes: null,
      pointsPossible: 100,
      score: 92,
      submittedAt: null,
      gradedAt: null,
      courseId: null,
      canvasAssignmentId: null,
      assignmentType: "assignment",
      hasSubmission: true,
      isGraded: true,
      isMissing: false,
      isLate: false,
      hasReplies: false,
    },
    {
      userId,
      courseName: "History Research Paper",
      subject: "History",
      status: "graded_on_time",
      dueDate: "Feb 10",
      weight: 20,
      completed: true,
      grade: 98,
      notes: null,
      pointsPossible: 100,
      score: 98,
      submittedAt: null,
      gradedAt: null,
      courseId: null,
      canvasAssignmentId: null,
      assignmentType: "assignment",
      hasSubmission: true,
      isGraded: true,
      isMissing: false,
      isLate: false,
      hasReplies: false,
    },
    {
      userId,
      courseName: "Physics Lab Report 3",
      subject: "Physics",
      status: "graded_on_time",
      dueDate: "Feb 5",
      weight: 10,
      completed: true,
      grade: 94,
      notes: null,
      pointsPossible: 100,
      score: 94,
      submittedAt: null,
      gradedAt: null,
      courseId: null,
      canvasAssignmentId: null,
      assignmentType: "assignment",
      hasSubmission: true,
      isGraded: true,
      isMissing: false,
      isLate: false,
      hasReplies: false,
    },
    {
      userId,
      courseName: "Spanish Oral Presentation",
      subject: "Spanish",
      status: "graded_on_time",
      dueDate: "Jan 28",
      weight: 8,
      completed: true,
      grade: 96,
      notes: null,
      pointsPossible: 100,
      score: 96,
      submittedAt: null,
      gradedAt: null,
      courseId: null,
      canvasAssignmentId: null,
      assignmentType: "assignment",
      hasSubmission: true,
      isGraded: true,
      isMissing: false,
      isLate: false,
      hasReplies: false,
    },
    {
      userId,
      courseName: "Art Portfolio Review",
      subject: "Art",
      status: "graded_on_time",
      dueDate: "Jan 20",
      weight: 12,
      completed: true,
      grade: 91,
      notes: null,
      pointsPossible: 100,
      score: 91,
      submittedAt: null,
      gradedAt: null,
      courseId: null,
      canvasAssignmentId: null,
      assignmentType: "assignment",
      hasSubmission: true,
      isGraded: true,
      isMissing: false,
      isLate: false,
      hasReplies: false,
    },
    {
      userId,
      courseName: "Chemistry Midterm",
      subject: "Chemistry",
      status: "graded_on_time",
      dueDate: "Jan 15",
      weight: 25,
      completed: true,
      grade: 93,
      notes: null,
      pointsPossible: 100,
      score: 93,
      submittedAt: null,
      gradedAt: null,
      courseId: null,
      canvasAssignmentId: null,
      assignmentType: "assignment",
      hasSubmission: true,
      isGraded: true,
      isMissing: false,
      isLate: false,
      hasReplies: false,
    },
    {
      userId,
      courseName: "PE Fitness Assessment",
      subject: "PE",
      status: "graded_on_time",
      dueDate: "Jan 10",
      weight: 5,
      completed: true,
      grade: 100,
      notes: null,
      pointsPossible: 100,
      score: 100,
      submittedAt: null,
      gradedAt: null,
      courseId: null,
      canvasAssignmentId: null,
      assignmentType: "assignment",
      hasSubmission: true,
      isGraded: true,
      isMissing: false,
      isLate: false,
      hasReplies: false,
    },
  ];

  for (const a of assignmentData) {
    await storage.createAssignment(a);
  }
}

export async function seedDatabase() {
  const existing = await db.select().from(users).where(eq(users.username, "demo"));
  if (existing.length > 0) {
    const existingAssignments = await storage.getAssignments(existing[0].id);
    if (existingAssignments.length > 0) {
      return;
    }
    await seedAssignments(existing[0].id);
    return;
  }

  const user = await storage.createUser({
    username: "demo",
    password: "demo123",
    fullName: "Solace",
    email: "solace@student.edu",
    schoolAffiliation: "Pasadena High School",
  });

  await storage.updateUser(user.id, {
    canvasBaseUrl: "https://pasadena.instructure.com",
    canvasConnected: false,
  });

  await seedAssignments(user.id);
}
